#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# ///
"""pr-sync — render a PR's claim-status block from the LIVE state of the issues it claims.

A draft PR is an implementation transaction against a subtree of the roadmap issue
tree. It declares the issues it claims with a marker in its body:

    <!-- claims: 31 32 57 -->

and carries a generated region:

    <!-- claim-status:start -->
    ...generated by this script...
    <!-- claim-status:end -->

This walks each claimed issue's sub-issue subtree, reads open/closed state from
GitHub, and rewrites the region with a nested checklist (checked == issue closed).

The boxes are a PROJECTION of real state, never hand-edited. Completion truth is
"issue closed on merge + its proofs green", not a self-checked box — so the block
cannot go stale and a resuming agent can trust it. Run from CI (or `just pr-sync N`)
on push; the agent never ticks a box.
"""
import json
import os
import re
import subprocess
import sys
import tempfile

CLAIMS_RE = re.compile(r"<!--\s*claims:\s*([0-9 ,#]+?)\s*-->")
START = "<!-- claim-status:start -->"
END = "<!-- claim-status:end -->"


def gh(*args: str) -> str:
    return subprocess.run(["gh", *args], check=True, capture_output=True, text=True).stdout


def gh_json(*args: str):
    return json.loads(gh(*args))


def repo() -> str:
    return gh_json("repo", "view", "--json", "nameWithOwner")["nameWithOwner"]


def issue(nwo: str, n: int) -> dict:
    return gh_json("api", f"repos/{nwo}/issues/{n}", "--jq", "{number,title,state}")


def sub_numbers(nwo: str, n: int) -> list[int]:
    out = gh("api", f"repos/{nwo}/issues/{n}/sub_issues", "--jq", "[.[].number]")
    return json.loads(out or "[]")


def build(nwo: str, n: int, seen: set[int]) -> dict | None:
    if n in seen:
        return None
    seen.add(n)
    node = issue(nwo, n)
    node["children"] = [c for k in sub_numbers(nwo, n) if (c := build(nwo, k, seen))]
    return node


def render(node: dict, depth: int = 0) -> list[str]:
    box = "x" if node["state"] == "closed" else " "
    lines = [f'{"  " * depth}- [{box}] #{node["number"]} {node["title"]}']
    for c in node["children"]:
        lines += render(c, depth + 1)
    return lines


def counts(node: dict) -> tuple[int, int]:
    done = 1 if node["state"] == "closed" else 0
    total = 1
    for c in node["children"]:
        d, t = counts(c)
        done += d
        total += t
    return done, total


def parse_claims(body: str) -> list[int] | None:
    m = CLAIMS_RE.search(body)
    return [int(x) for x in re.findall(r"\d+", m.group(1))] if m else None


def replace_region(body: str, content: str) -> str:
    block = f"{START}\n{content}\n{END}"
    if START in body and END in body:
        return re.sub(re.escape(START) + r".*?" + re.escape(END), lambda _: block, body, count=1, flags=re.S)
    m = CLAIMS_RE.search(body)
    if m:
        i = m.end()
        return body[:i] + "\n\n" + block + body[i:]
    return body.rstrip() + "\n\n" + block + "\n"


def sync(pr: int) -> None:
    nwo = repo()
    body = gh_json("pr", "view", str(pr), "--json", "body")["body"]
    claims = parse_claims(body)
    if not claims:
        print(f"PR #{pr} has no `<!-- claims: N N -->` marker; not a tree-claim PR, skipping.")
        return
    seen: set[int] = set()
    roots = [r for n in claims if (r := build(nwo, n, seen))]
    done = sum(counts(r)[0] for r in roots)
    total = sum(counts(r)[1] for r in roots)
    head = (
        f"**Claim status: {done}/{total} claimed issues closed.** "
        "_Generated from live issue state by `just pr-sync` — do not hand-edit. "
        "Completion = issue closed on merge + green proofs, not a checked box._"
    )
    lines = [head, ""]
    for r in roots:
        lines += render(r)
    new = replace_region(body, "\n".join(lines))
    if new == body:
        print("no change")
        return
    with tempfile.NamedTemporaryFile("w", suffix=".md", delete=False) as f:
        f.write(new)
        tmp = f.name
    gh("pr", "edit", str(pr), "--body-file", tmp)
    os.unlink(tmp)
    print(f"synced PR #{pr}: {done}/{total} claimed issues closed")


def check() -> None:
    """Offline self-test of the pure functions (no network)."""
    tree = {
        "number": 1, "title": "root", "state": "open", "children": [
            {"number": 2, "title": "a", "state": "closed", "children": []},
            {"number": 3, "title": "b", "state": "open", "children": []},
        ],
    }
    assert counts(tree) == (1, 3), counts(tree)
    r = "\n".join(render(tree))
    assert "- [ ] #1 root" in r and "  - [x] #2 a" in r and "  - [ ] #3 b" in r, r
    assert parse_claims("x <!-- claims: 31, #32 57 --> y") == [31, 32, 57]
    assert parse_claims("no marker") is None
    b = f"A\n{START}\nOLD\n{END}\nB"
    assert replace_region(b, "NEW") == f"A\n{START}\nNEW\n{END}\nB"
    assert START in replace_region("hi <!-- claims: 1 --> bye", "NEW")
    print("pr-sync self-check OK")


if __name__ == "__main__":
    if len(sys.argv) >= 2 and sys.argv[1] == "--check":
        check()
    elif len(sys.argv) >= 2:
        sync(int(sys.argv[1]))
    else:
        sys.exit("usage: pr-sync.py <pr-number> | --check")
